### ISSUE TITLE
Undefined method `locals'

### ISSUE THREAD

**Issue by steakknife** [hanami/view#153]
Maybe I'm holding it wrong, but it looks like an API changed or something didn't load properly. Suggestions or is this a bug?

### MCE

```
gem install hanami -v 1.2.0
gem install haml -v 5.0.4
hanami new Bookstore --database=postgres --test=rspec --template=haml
HANAMI_ENV=test bundle exec hanami db create
rake spec
```

### Output

```
Failures:

  1) Web::Views::ApplicationLayout contains application name
     Failure/Error: let(:rendered) { layout.render }

     NoMethodError:
       undefined method `locals' for #<Hanami::View::Template:0x00007fd3ce6adfc0>
     # ~/.gem/ruby/2.5.1/gems/hanami-view-1.2.0/lib/hanami/view/rendering/layout_scope.rb:233:in `method_missing'
     # ~/.gem/ruby/2.5.1/gems/tilt-2.0.8/lib/tilt/haml.rb:23:in `evaluate'
     # ~/.gem/ruby/2.5.1/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
     # ~/.gem/ruby/2.5.1/gems/hanami-view-1.2.0/lib/hanami/view/template.rb:41:in `render'
     # ~/.gem/ruby/2.5.1/gems/hanami-view-1.2.0/lib/hanami/layout.rb:139:in `render'
     # ./spec/web/views/application_layout_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/web/views/application_layout_spec.rb:9:in `block (2 levels) in <top (required)>'

Finished in 0.00574 seconds (files took 2.33 seconds to load)
1 example, 1 failure
```

### Versions

- macOS 10.13.6 (17G65)
- ruby 2.5.1
- gem 2.7.7

#### Gem Versions

haml (5.0.4)
haml-lint (0.999.999)
haml-rails (1.0.0)
haml_lint (0.28.0)
hanami (1.2.0)
hanami-assets (1.2.0)
hanami-cli (0.2.0)
hanami-controller (1.2.0)
hanami-helpers (1.2.2)
hanami-mailer (1.2.0)
hanami-model (1.2.0)
hanami-router (1.2.0)
hanami-utils (1.2.0)
hanami-validations (1.2.2)
hanami-view (1.2.0)
hanami-webconsole (0.1.0)
[more...](https://gist.github.com/steakknife/d87a3fcc6b00c8759608298ecf19ce49)
